# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddbuild < Formula
  desc "Process concise files and use templates to generate Datadog input files for CI support."
  homepage ""
  version "0.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/wishabi/datadog-helper-go/releases/download/v0.2/datadog-helper-go_0.2_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryDownloadStrategy
    sha256 "9c42fb3d52dd388c169db72542e7ecb6753a02afe6263595fa7512e3ae27ee41"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/wishabi/datadog-helper-go/releases/download/v0.2/datadog-helper-go_0.2_Darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryDownloadStrategy
    sha256 "db7b85c94607b1e1b0a1ebecdb08415431f900c3d603a46b72eb89bfb747c99f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/wishabi/datadog-helper-go/releases/download/v0.2/datadog-helper-go_0.2_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryDownloadStrategy
    sha256 "52485d75a0f1f8940b217be3a6a77eb1062ca7274307ffed353ea53460ad183f"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/wishabi/datadog-helper-go/releases/download/v0.2/datadog-helper-go_0.2_Linux_arm64.tar.gz", :using => GitHubPrivateRepositoryDownloadStrategy
    sha256 "c48514523ccd781507e20710b6eecba89ade2ed5cfd42b18f864ca9ce4b1c3df"
  end

  def install
    bin.install "datadog-helper-go"
  end
end
