# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Ddbuild < Formula
  desc "Process concise files and use templates to generate Datadog input files for CI support."
  homepage ""
  version "0.2.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/wishabi/datadog-helper-go/releases/download/v0.2.1/datadog-helper-go_0.2.1_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "4d93bc1b3b9528829a8fce3f375c1b68a3551697a44b37abf27cdf3fa58867ce"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/wishabi/datadog-helper-go/releases/download/v0.2.1/datadog-helper-go_0.2.1_Darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "6fee99979323f40857b306e6c2384b5d7b83ea387b194a27bbbed5e0d8cacc1e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/wishabi/datadog-helper-go/releases/download/v0.2.1/datadog-helper-go_0.2.1_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "f0b20287f2afe3789beb5da13c89ffc78823c9751d8667c03dd006fff3ef73fb"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/wishabi/datadog-helper-go/releases/download/v0.2.1/datadog-helper-go_0.2.1_Linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "fea5bd46c9a855b36561e32eb7e8c3b8797f87d97d6748b9278a70d8171ccea6"
  end

  def install
    bin.install "datadog-helper-go"
  end
end
