# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/private"
class Ddbuild < Formula
  desc "Process concise files and use templates to generate Datadog input files for CI support."
  homepage ""
  version "0.2.14"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/wishabi/datadog-helper-go/releases/download/0.2.14/ddbuild_0.2.14_darwin_amd64.tar.gz", :using => :github_private_release
    sha256 "cbdbb2192d914201b2b2730a31d1bbcbf5297e59f706f483710121f3ec5bfac8"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/wishabi/datadog-helper-go/releases/download/0.2.14/ddbuild_0.2.14_darwin_arm64.tar.gz", :using => :github_private_release
    sha256 "f5ba282e32127ecef262c08d4ebfb6bad0e1317c0c0b5fc7ac0cae736464c731"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/wishabi/datadog-helper-go/releases/download/0.2.14/ddbuild_0.2.14_linux_amd64.tar.gz", :using => :github_private_release
    sha256 "0611ca8a08c7787bfc46d0be28e51180821c38bc3471ab6c942ce8f4c5b90f12"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/wishabi/datadog-helper-go/releases/download/0.2.14/ddbuild_0.2.14_linux_arm64.tar.gz", :using => :github_private_release
    sha256 "3a6caab22b2034c735d8e2b3c658d5f4457ebb8ea4c13da245e80dab33c5ab6d"
  end

  def install
    bin.install "ddbuild"
  end
end
