# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GlobalDockerCompose < Formula
  desc "Standardized and centralized Docker compose command"
  homepage ""
  version "0.10.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wishabi/global-docker-compose/releases/download/v0.10.1/global_docker_compose_0.10.1_darwin_amd64.tar.gz"
      sha256 "82062717d3e6e9ea54027379f0b8ba4cfd312def5522db5149bf9097285cdc9a"

      def install
        bin.install "global_docker_compose"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wishabi/global-docker-compose/releases/download/v0.10.1/global_docker_compose_0.10.1_darwin_arm64.tar.gz"
      sha256 "4865a5e81df13bca1aa2f693bb9efa706937abbbae0d6118bb7ebbf36744dac6"

      def install
        bin.install "global_docker_compose"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wishabi/global-docker-compose/releases/download/v0.10.1/global_docker_compose_0.10.1_linux_amd64.tar.gz"
      sha256 "625d0d7d575012cb07fdc13d6e937c1512d39ce49a05b3d2de240c6c1d179b16"

      def install
        bin.install "global_docker_compose"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wishabi/global-docker-compose/releases/download/v0.10.1/global_docker_compose_0.10.1_linux_arm64.tar.gz"
      sha256 "3ab369a8c50ab48ebb75f4fd4fcfd9aff15209b7804b0f11a082920e5767457e"

      def install
        bin.install "global_docker_compose"
      end
    end
  end
end
